-- Create Users table
CREATE TABLE Users (
    ID INT NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Login VARCHAR(50) NOT NULL,
    Password VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE(Login)
);

-- Create Contacts table
CREATE TABLE Contacts (
    ID INT NOT NULL AUTO_INCREMENT,
    UserID INT NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Phone VARCHAR(20),
    PRIMARY KEY (ID),
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON DELETE CASCADE
);